sudo: required
services:
  - docker
language: python
python:
  - "2.7"
env:
  matrix:
    - IMAGE=centos6
    - IMAGE=centos7
install:
  - pip install testinfra
script:
  - ./run-tests.py test $IMAGE -v
